language: node_js
os:
- linux
node_js:
- node
script:
- npm install
- npm run deploy
env:
  matrix:
    secure: gOy7Zv2pzHOCtuP7Ry0GlGlLBU/F1qrqLsz2ORStxosSlGh22RI2Z3kS4G6maxdsvOL0DXbb/mVLJbz4i7gDGclHPFUc3DNyb/0DXPj9lWBVOrMR9oTwxCbUnU1novkmvdsPT6ZLwbgOe2Mc4xk+FrZG5SaLSTa+ZfckwHxIN8t3dg9EUxfyKOM+wCSAzm5RIdM02tuRUllmW5q+AaSBKhUrAUfICTM6+mrEvNoo1QCq8avMIfPGgoOWOCkQjNSSTuqQUFzhrHzikW7ydaUU27OfKut847ARLp1bOA27ycLwyxI14mygVQujUKxUhJ/yKThfi2aKT5553AKw0GKV6uRXu2VwFOiQadgjBqoyawtx6a8HaMExudciFB9f5C0nfIF/xvinDdTEV0iqBr2jAzXDN/SQDKCZuTqdnsRFzrDvw3Rs/EM850TiHOfVTEodIC70Aclc+/Ajcqpfz18VWUoMtCnQTVRINxWE9Cb6pI7KxJfQL/c61oWeAOJ284YbpJIUCGvk0MPmJlsqgN2RO4IYbRjN7Pk6PAau4wXGhE4xgwhCpX225J+Rj9gROjUDCLGfRZllJtGJtD8u1de5dOLzj3YKoC5JrTpkyyGygMqIzDWikkue/Ylp1mYhPA/WXep56F3knLzgFHd4gBR2wqsiNvKfatKTrWcopqd3Usg=
